/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testContractSol from "./TestContract.sol";
export type { testContractSol };
import type * as testErc20Sol from "./TestERC20.sol";
export type { testErc20Sol };
export type { TestSelfDestruct } from "./TestSelfDestruct";
export type { TestTransfer } from "./TestTransfer";
