/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testContractSol from "./TestContract.sol";
export * as testErc20Sol from "./TestERC20.sol";
export { TestSelfDestruct__factory } from "./TestSelfDestruct__factory";
export { TestTransfer__factory } from "./TestTransfer__factory";
