/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface DepsUtilsInterface extends utils.Interface {
  functions: {
    "multipleDeps(address[],bytes32[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "multipleDeps"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "multipleDeps",
    values: [string[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "multipleDeps",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DepsUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DepsUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    multipleDeps(
      _wallets: string[],
      _ids: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  multipleDeps(
    _wallets: string[],
    _ids: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    multipleDeps(
      _wallets: string[],
      _ids: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    multipleDeps(
      _wallets: string[],
      _ids: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    multipleDeps(
      _wallets: string[],
      _ids: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
