/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "WalletImp",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WalletImp__factory>;
    getContractFactory(
      name: "TestOutOfGas",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestOutOfGas__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "TestSelfDestruct",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestSelfDestruct__factory>;
    getContractFactory(
      name: "TestTransfer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestTransfer__factory>;
    getContractFactory(
      name: "DepsUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DepsUtils__factory>;
    getContractFactory(
      name: "Wallet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Wallet__factory>;
    getContractFactory(
      name: "WalletFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WalletFactory__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "WalletImp",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WalletImp>;
    getContractAt(
      name: "TestOutOfGas",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestOutOfGas>;
    getContractAt(
      name: "MockERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "TestSelfDestruct",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestSelfDestruct>;
    getContractAt(
      name: "TestTransfer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestTransfer>;
    getContractAt(
      name: "DepsUtils",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DepsUtils>;
    getContractAt(
      name: "Wallet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Wallet>;
    getContractAt(
      name: "WalletFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WalletFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
